spring:
  datasource:
    url: jdbc:h2:mem:camunda
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://${DATABASE_ADDRESS:127.0.0.1}:5432/${DATABASE_NAME:faf-gw}?useSSL=false
#    name: faf-db-pg
#    username: ${DATABASE_USERNAME:postgres}
#    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true